{% set name = "auto_rxn" %}
{% set version = "2023.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/auto_rxn-{{ version }}.tar.gz
  sha256: 482101dc4f6474a15675c64bc4305bb34979e0037f88282afba3da45b526b4e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - auto_rxn=auto_rxn.__main__:main
    - auto-rxn=auto_rxn.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - platformdirs
    - click
    - happi
    - pandas
    - bluesky
    - suitcase-csv
    - packaging
    - tomli
    - tomli-w

test:
  imports:
    - auto_rxn
  commands:
    #- pip check  # bluesky recipe has bad depndencies, breaks pip check, should check once upstream fixed
    - auto_rxn --help
    - auto-rxn --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uw-madison-chem-shops/auto_rxn
  summary: Python package for running chemical reactions as defined by recipe files.
  dev_url: https://github.com/uw-madison-chem-shops/auto_rxn
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
